baseURL                = "https://nemodzilla.xyz/"
languageCode           = "fr-fr"
title                  = "Nemo's Website"
defaultContentLanguage = "fr"
hasCJKLanguage         = false

[[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

