[fr]
    languageName = "🇫🇷 Français"
    title        = "Site de Nemo"
    weight       = 1

    [fr.params.sidebar]
        subtitle = "Des writeups et d'autres choses"

    [[fr.menus.main]]
        identifier = "home"
        name       = "Accueil"
        url        = "/"
        weight     = 1
        [fr.menus.main.params]
            icon = "home"

    [[fr.menus.main]]
        identifier = "about"
        name       = "À propos"
        url        = "/about/"
        weight     = 2
        [fr.menus.main.params]
            icon = "user"

    [[fr.menus.main]]
        identifier = "writeups"
        name       = "Writeups"
        url        = "/post/"
        weight     = 3
        [fr.menus.main.params]
            icon = "chevron-right"

    [[fr.menus.main]]
        identifier = "tips"
        name       = "Astuces"
        url        = "/tips/"
        weight     = 4
        [fr.menus.main.params]
            icon = "dots"

    [[fr.menus.main]]
        identifier = "categories"
        name       = "Catégories"
        url        = "/categories/"
        weight     = 5
        [fr.menus.main.params]
            icon = "categories"

    [[fr.menus.main]]
        identifier = "search"
        name       = "Recherche"
        url        = "/search/"
        weight     = 6
        [fr.menus.main.params]
            icon = "search"

    [[fr.menus.main]]
        identifier = "archives"
        name       = "Archives"
        url        = "/archives/"
        weight     = 7
        [fr.menus.main.params]
            icon = "archives"

    [[fr.menus.social]]
        identifier = "github"
        name       = "GitHub"
        url        = "https://github.com/nemodzilla"
        weight     = 1
        [fr.menus.social.params]
            icon = "brand-github"

    [[fr.menus.social]]
        identifier = "linkedin"
        name       = "LinkedIn"
        url        = "https://www.linkedin.com/in/noemie-mancini/"
        weight     = 2
        [fr.menus.social.params]
            icon = "linkedin"

[en]
    languageName = "🇬🇧 English"
    title        = "Nemo's Website"
    weight       = 2

    [en.params.sidebar]
        subtitle = "Writeups & other things"

    [[en.menus.main]]
        identifier = "home"
        name       = "Home"
        url        = "/"
        weight     = 1
        [en.menus.main.params]
            icon = "home"

    [[en.menus.main]]
        identifier = "about"
        name       = "About"
        url        = "/about/"
        weight     = 2
        [en.menus.main.params]
            icon = "user"

    [[en.menus.main]]
        identifier = "writeups"
        name       = "Writeups"
        url        = "/post/"
        weight     = 3
        [en.menus.main.params]
            icon = "chevron-right"

    [[en.menus.main]]
        identifier = "tips"
        name       = "Tips"
        url        = "/tips/"
        weight     = 4
        [en.menus.main.params]
            icon = "dots"

    [[en.menus.main]]
        identifier = "categories"
        name       = "Categories"
        url        = "/categories/"
        weight     = 5
        [en.menus.main.params]
            icon = "categories"

    [[en.menus.main]]
        identifier = "search"
        name       = "Search"
        url        = "/search/"
        weight     = 6
        [en.menus.main.params]
            icon = "search"

    [[en.menus.main]]
        identifier = "archives"
        name       = "Archives"
        url        = "/archives/"
        weight     = 7
        [en.menus.main.params]
            icon = "archives"

    [[en.menus.social]]
        identifier = "github"
        name       = "GitHub"
        url        = "https://github.com/nemodzilla"
        weight     = 1
        [en.menus.social.params]
            icon = "brand-github"

    [[en.menus.social]]
        identifier = "linkedin"
        name       = "LinkedIn"
        url        = "https://www.linkedin.com/in/noemie-mancini/"
        weight     = 2
        [en.menus.social.params]
            icon = "linkedin"