[fr]
    languageName = "🇫🇷 Français"
    title        = "Site de Nemo"
    weight       = 1

    [fr.params.sidebar]
        subtitle = "Des writeups et d'autres choses"

    [[fr.menus.main]]
        identifier = "home"
        name       = "Accueil"
        url        = "/"
        weight     = 1
        [fr.menus.main.params]
            icon = "home"

    [[fr.menus.main]]
        identifier = "writeups"
        name       = "Writeups"
        url        = "/fr/post/"
        weight     = 2
        [fr.menus.main.params]
            icon = "hash"

    [[fr.menus.main]]
        identifier = "categories"
        name       = "Catégories"
        url        = "/fr/categories/"
        weight     = 3
        [fr.menus.main.params]
            icon = "categories"

    [[fr.menus.main]]
        identifier = "search"
        name       = "Recherche"
        url        = "/fr/search/"
        weight     = 4
        [fr.menus.main.params]
            icon = "search"

    [[fr.menus.main]]
        identifier = "archives"
        name       = "Archives"
        url        = "/fr/archives/"
        weight     = 5
        [fr.menus.main.params]
            icon = "archives"

[en]
    languageName = "🇬🇧 English"
    title        = "Nemo's Website"
    weight       = 2

    [en.params.sidebar]
        subtitle = "Writeups & other things"

    [[en.menus.main]]
        identifier = "home"
        name       = "Home"
        url        = "/"
        weight     = 1
        [en.menus.main.params]
            icon = "home"

    [[en.menus.main]]
        identifier = "writeups"
        name       = "Writeups"
        url        = "/en/post/"
        weight     = 2
        [en.menus.main.params]
            icon = "hash"

    [[en.menus.main]]
        identifier = "categories"
        name       = "Categories"
        url        = "/en/categories/"
        weight     = 3
        [en.menus.main.params]
            icon = "categories"

    [[en.menus.main]]
        identifier = "search"
        name       = "Search"
        url        = "/en/search/"
        weight     = 4
        [en.menus.main.params]
            icon = "search"

    [[en.menus.main]]
        identifier = "archives"
        name       = "Archives"
        url        = "/en/archives/"
        weight     = 5
        [en.menus.main.params]
            icon = "archives"

