mainSections   = ["post", "tips"]
rssFullContent = true
favicon        = "img/avatar.png"

[footer]
    since = 2024

[sidebar]
    emoji    = "💤"
    subtitle = "Nemo's website"

        [sidebar.avatar]
            enabled = true
            local   = true
            src     = "img/avatar.png"

[article]
    [article.license]
        enabled = false


[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    enabled  = false
    provider = "disqus"

[cookies]
    enabled = false

[colorScheme]
    toggle  = true
    default = "auto"

    [cookies.categories]
        analytics  = true
        functional = true
